[package]
name = "boot_script"
version = "0.1.0"
authors = ["launch-cmd"]
edition = "2018"

[dependencies]
cmd_lib = { path = "../cmd_lib"}
structopt = "0.3.21"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
